repos:
    -   repo: https://github.com/asottile/pyupgrade
        rev: v2.32.1
        hooks:
        -   id: pyupgrade
            args: [--py37-plus]

    -   repo: https://github.com/pycqa/isort
        rev: 5.10.1
        hooks:
        -    id: isort
             additional_dependencies: ["colorama>=0.4.3"]

    -   repo: https://github.com/psf/black
        rev: 22.3.0
        hooks:
        -   id: black
            args: [--skip-magic-trailing-comma]

    -   repo: https://gitlab.com/pycqa/flake8.git
        rev: 3.9.2
        hooks:
        -   id: flake8

    -   repo: https://github.com/pycqa/pydocstyle
        rev: 6.1.1
        hooks:
        -   id: pydocstyle
            exclude: (tests|docs|experiments)
            additional_dependencies: ["toml"]

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.971
        hooks:
        -   id: mypy
            args: [--strict, --ignore-missing-imports, --show-error-codes]
            additional_dependencies: ['types-requests', 'types-python-dateutil']
            exclude: (build|data|dist|logo|logs|output)/

    -   repo: local
        hooks:
        -   id: check-autogens
            name: Check Autogen Files
            entry: ./util/check-autogens.sh
            language: script
            pass_filenames: false
