default_collection:
  outdir: data
  # datetime: 2013-04-02/2019-07-17  # full ASO range
  datetime: 2019-11-01/2020-05-01
  aoi_file: config/aoi/aso-2013-2019-regions.json

providers: 
    - id: MPC
      collections: 
        - id: sentinel-1-rtc
          assets:
            - all

system:
  dry_run: True
  query_asset_sizes: True